### ISSUE TITLE
Hover popup conflicts with LSP-Vue, LSP-Volar on ST 4113

### ISSUE THREAD

**Issue by faaizajaz** [sublimelsp/LSP-tailwindcss#19]
This package seems to have some conflicts with LSP-Vue which prevents one from working while the other is enabled. I have both enabled in a project and it is a toss-up as to which will work when I open ST.

Completions seem to be workingOK for both Tailwind and Vue servers, but I am not getting the code intel when hovering over tailwind classes. If I disable LSP-Vue, then the popups work as expected.

I get the same behavior with LSP-Volar. Using the latest version on Package Control for all plugin.

No errors to note in console, it seems to load all language servers just fine.

Am I missing something obvious here?

**Comment by predragnikolic** [comment]
Thanks for the issue @faaizajaz.
I created a PR that should resolve it.

**Comment by faaizajaz** [comment]
@predragnikolic nice, that was quick! Thanks--hope it gets accepted soon.

**Comment by rchl** [comment]
While fixing the bug is good, running both LSP-vue and LSP-vetur will result in a lot of duplicated content in the popups. Not a good idea IMO.

You can instead disable hover provider for one of them so that you consistently only get one of them in the popup. See https://github.com/sublimelsp/LSP-pylsp#running-alongside-lsp-pyright on how to do it.

**Comment by faaizajaz** [comment]
@rchl can't say I haven't made that mistake in the past. Took me way too long to figure out why I was getting duplicate color previews (spoiler alert: it was a conflict between LSP-css and the ColorHelper plugin)

**Comment by predragnikolic** [comment]
The PR was merged.
I will keep the issue open untill we see a new release of LSP.

**Comment by faaizajaz** [comment]
Quick question: if I clone the LSP repo to my packages folder to get the fix before the next release, will that automatically integrate with PackageControl, or will I need to manually update when a new release is made?

**Comment by predragnikolic** [comment]
If you clone it, than you won't receive automatic updates from PC. You would have to manually update.

**Comment by predragnikolic** [comment]
There is a new version of LSP published on PC that includes this fix 🙂

**Comment by faaizajaz** [comment]
@predragnikolic huge thanks for this
