### ISSUE TITLE
Disable suggestions

### ISSUE THREAD

**Issue by AbeEstrada** [sublimelsp/LSP-tailwindcss#40]
Is there an option to disable the suggestions?

When I write classes it is very laggy for me, I want all the other options but the autocomplete/suggestions.

The [server](https://github.com/tailwindlabs/tailwindcss-intellisense) has the option `tailwindCSS.suggestions`, I forked the project and tried to add it but doesn't work. Obviously I have no idea how to send LSP settings to the server on Sublime Text. I hope you can point me to the right direction.

Thanks.

**Comment by rchl** [comment]
No need to fork anything. Just open `Preferences: LSP-tailwindcss Settings` and put this on the right side:

```js
{
    "settings": {
        "tailwindCSS.suggestions": false,
    }
}
```

Alternatively use the client feature to disable completions which is even better as it will prevent from even asking the server for completions:

```js
{
    "disabled_capabilities": {
        "completionProvider": true,
    }
}
```

**Comment by AbeEstrada** [comment]
Thank you

**Comment by rchl** [comment]
Note that `tailwindCSS.suggestions` is missing from the schema bundled with this package so it will result in a warning when using `LSP-json`. This is something that could be fixed.
