### ISSUE TITLE
Use with Elixir - Phoenix Framework

### ISSUE THREAD

**Issue by sukinoverse** [sublimelsp/LSP-tailwindcss#42]
### Create webapp project
- Create a new Phoenix project with `mix phx.new`
- Add tailwind to Phoenix via https://github.com/phoenixframework/tailwind

**Noted:** Phoenix approach is to use standalone tailwind because Phoenix is escape away from node / webpack world, so no node_module inside.

### Install LSP on Sublime
- Install `LSP-tailwindcss` on Sublime
- Add `text.html.elixir` to `LSP-tailwindcss selector config` 

## Problem
`LSP-tailwindcss` is started and active for elixir HTML template file.
But looks like it's not working, no suggestion, auto-complete and warning given for wrong tailwind class.

<img width="1552" alt="Screen Shot 2022-07-09 at 15 21 58" src="https://user-images.githubusercontent.com/9070844/178098566-d4b34773-2a42-42bc-82cb-bc89af583d56.png">

**Comment by sukinoverse** [comment]
Oh, I just found this comment https://github.com/sublimelsp/LSP-tailwindcss/issues/34#issuecomment-1173915567
Looks like adding `"text.html.elixir": "html"` to LSP Language ID overrides make it works with Elixir too.

I hope we can have better solution for this 😅

**Comment by predragnikolic** [comment]
In the new version of LSP-tailwindcss and LSP.

You no longer need to override the language ids 
and you no longer need to add the `"text.html.elixir"` to the selector.

Just give PackageControl 1 to 3h to pick up the new LSP 4070-1.20.0 release.

**Comment by predragnikolic** [comment]
Also thanks for this issue!
It is pretty good report :)
