### ISSUE TITLE
TailwindCSS and LSP-Tailwind config

### ISSUE THREAD

**Issue by jeff-grinta** [sublimelsp/LSP-tailwindcss#43]
Hi,

I'm trying to get [TailwindCSS](https://github.com/SublimeText/TailwindCSS) to work along side LSP-Tailwind.
By default when setting the language to CSS, LSP features work out of the box. However when setting it to Tailwind CSS these features are disabled.
I've tried to add the following to the config:
`source.css.tailwind` to `"selector"
```json
{
	"languageId": "css",
	"scopes": ["source.css", "source.css.tailwind"],
	"syntaxes": [
		"Packages/CSS/CSS.sublime-syntax",
		"Packages/CSS3/CSS3.sublime-syntax",
		"Packages/Tailwind CSS/Tailwind CSS.sublime-syntax"
	]
},
```
to `"languages"` but it didn't change anything.

Any idea on how to get the two working together?

**Comment by predragnikolic** [comment]
Cannot reproduce.
LSP-tailwindcss.sublime-settings looks like this:
```
{
    "selector": "source.jsx | source.js.react | source.js | source.tsx | source.ts | source.css | source.scss | source.less | text.html.vue | text.html.svelte | text.html.basic | text.html.twig | text.blade | embedding.php | text.html.rails | text.haml | source.css.tailwind"
}
```

![Screenshot 2022-08-10 at 16 19 21](https://user-images.githubusercontent.com/22029477/183925694-4852d402-0c8e-4627-87df-38c2e9eb5b47.png)


NOTE: the LSP-tailwindcss server will start in a project that has tailwind.config.js in the project(as mentioned in the readme https://github.com/sublimelsp/LSP-tailwindcss#installation)

**Comment by predragnikolic** [comment]
I will close they because this can't be reproduced.

Feel free to reopen this issue if it still exist, but please provide a repository to reproduce the issue.
