### ISSUE TITLE
Not Giving quick suggestion in Sublime Text 4 And also Not Installing from Package:Install 

### ISSUE THREAD

**Issue by divyamrit** [sublimelsp/LSP-tailwindcss#5]
So, I install it through git but It only shown color in front bg-{Any_tailwindcss_Colors}-{Any_Number}00, Else it done nothing. I also configure setting but it didn't work . Please Help me Out.

**Comment by predragnikolic** [comment]
This plugin is not yet released to Package Control. (But I will try to make it available on Package Control as soon as I grab some free time :) )

Can you provide minimal reproduction steps, or a gif/video demonstrating the problem?

**Comment by divyamrit** [comment]
There are Two dependencies are missing I see the promt. In sublime Text

**Comment by divyamrit** [comment]
So that's Why it was not autocompleting Thanks.
