### ISSUE TITLE
Nothing happens only on Elixir Files/Templates

### ISSUE THREAD

**Issue by gdgp** [sublimelsp/LSP-tailwindcss#56]
Hi!

I'm having an issue in which it runs perfectly in say, an HTML file (autocomplete, hover information, etc), but in Elixir template files (e.g. `eex`, `heex`, `leex` or even in some `ex` with html information in them) it does not. I can see that the language server is triggered in the status bar, but nothing happens.

Strange part is that if I rename the file to for example an html or a php and reopen it, it works perfectly.

From looking into [this](https://github.com/sublimelsp/LSP-tailwindcss/issues/42) closed issue I don't think I would need any special configuration. But, I've tried specifically adding it and some other  `includeLanguages`, for the several different combinations, etc, but no luck -- to be fair, I already see the language server triggered.

The only message I see in the console log (even with LSP debug mode enabled), but which I think is not related since it also appears in the case I renamed it to an extension where it works is:
```
Found styles linked in HTML
[]
```

Any clue what the issue could be?

Thanks in advance

**Comment by predragnikolic** [comment]
Hello,
Can you provide steps to reproduce it?

**Comment by gdgp** [comment]
Hi @predragnikolic 

Of course, I just created a sample project where the same happens to me. Some notes on it:
- here is the sample project: [hello.zip](https://github.com/sublimelsp/LSP-tailwindcss/files/10848694/hello.zip)
- look for `sample.html` and `sample.html.eex` to see the differences
- here are a couple of screenshots that illustrate the situation (one works the other does not)

Works:
<img width="1719" alt="Screenshot 2023-02-28 at 09 32 46" src="https://user-images.githubusercontent.com/6975450/221813518-df59833a-66af-4b93-bbdc-1430bc53379c.png">

Does not work:
<img width="1715" alt="Screenshot 2023-02-28 at 09 31 09" src="https://user-images.githubusercontent.com/6975450/221813677-1f429a5e-c7d3-4db2-a396-f711dd17a4c4.png">

**Comment by rchl** [comment]
What's the root scope of that EEx syntax? You can see by triggering menu: Tools -> Developer -> Show scope name.

I think typically those are handled by adding a mapping for the scope (language id) in `tailwindCSS.includeLanguages`.

**Comment by rchl** [comment]
Actually in this (hidden) setting: https://github.com/sublimelsp/LSP-tailwindcss/issues/51

**Comment by gdgp** [comment]
The scope is `text.html.eex`, I've played around with the mapping you mentioned but I was not successfull.

Latest attempt a bit all over the place:

1. LSP-tailwindcss.sublime-settings:
```json
// Settings in here override those in "LSP-tailwindcss/LSP-tailwindcss.sublime-settings"

{
  "settings": {
    "tailwindCSS.includeLanguages": {
      "text.html.eex": "html"
    },
  },
  "selector": "source.jsx | source.js.react | source.js | source.tsx | source.ts | source.css | source.scss | source.less | text.html.vue | text.html.svelte | text.html.basic | text.html.twig | text.blade | text.html.blade | embedding.php | text.html.rails | text.html.erb | text.haml | text.jinja | text.django | text.html.elixir | text.html.eex"
}

```

2. LSP.sublime-settings (sorry I'm not sure what I'm doing here so just tried several): 
```json
// Settings in here override those in "LSP/LSP.sublime-settings"
{
  "lsp_format_on_save": true,
  "log_debug": false,
  "initializationOptions": {
        "userLanguages": {
            "tailwind": "css",
            "tailwind": "text.html.eex",
            "text.html.eex": "html"
        },
    },
}
```

**Comment by rchl** [comment]
Try:

![Screenshot 2023-02-28 at 12 26 11](https://user-images.githubusercontent.com/153197/221840416-aaac1b4e-5bde-48da-be19-294e9b64f8ac.png)

```
// SublimeText base scope -> LSP Language ID overrides
{
    "text.html.eex": "html"
}
```

**Comment by gdgp** [comment]
@rchl thanks!

For the reference I added:
```json
// SublimeText base scope -> LSP Language ID overrides
{
  "text.html.eex": "html",
  "text.html.heex": "html",
  "text.html.leex": "html"
}
```

Which finally worked paired with appending to the selector ` | text.html.eex | text.html.leex | text.html.heex`:
```json
// Settings in here override those in "LSP-tailwindcss/LSP-tailwindcss.sublime-settings"
{
  "selector": "source.jsx | source.js.react | source.js | source.tsx | source.ts | source.css | source.scss | source.less | text.html.vue | text.html.svelte | text.html.basic | text.html.twig | text.blade | text.html.blade | embedding.php | text.html.rails | text.html.erb | text.haml | text.jinja | text.django | text.html.elixir | text.html.eex | text.html.leex | text.html.heex"
}
```

Thanks a lot for the quick help @rchl and @predragnikolic
