### ISSUE TITLE
Per project settings

### ISSUE THREAD

**Issue by davidwebca** [sublimelsp/LSP-tailwindcss#6]
I don't think that's currently possible for packages to have their configurations overridden by the project settings (according to the doc), but I wonder if there's anything you can do as the developer of the extension. 

My question comes from the fact that there's a setting called "tailwindCSS.rootFontSize" which allows to specify the root font-size so that the pixel values gets calculated and shown in the tooltips. This root font-size changes widely depending on the project and I'd like to be able to fix that with the ".sublime-project" file. In VScode there's workspace configs, but in Sublime the doc specifically states 

> Note that only settings in the category Editor Settings may be controlled by a project.

I don't know if that refers only to the "settings" key at the root level or if there's actually a way for users to override package configs. 🤔

**Comment by rchl** [comment]
LSP-* package settings can be overridden per-project. This should work in the project settings.
```
{
   // ...
	"settings": {
		"LSP": {
			"LSP-tailwindcss": {
				"settings": {
					"tailwindCSS.rootFontSize": 16
				}
			}
		}
	},
}
```

**Comment by davidwebca** [comment]
POG. Thanks so much, I tried various naming to construct my settings and test if it would work, but I probably never landed on it. 🔥

**Comment by rchl** [comment]
With https://github.com/sublimelsp/LSP-tailwindcss/pull/4 PR integrated and `LSP-json` installed there will be validation and auto-completion of settings, also within a project file. So that helps with discovery.
