### ISSUE TITLE
No example for twin.macro

### ISSUE THREAD

**Issue by JGJP** [sublimelsp/LSP-tailwindcss#67]
I intend to submit a pull request for this, but am posting the solution here for now:

```js
{
	"settings": {
		"tailwindCSS.experimental.classRegex": [
			"tw`([^`]*)",
			"tw=\"([^\"]*)",
			"tw={\"([^\"}]*)",
			"tw\\.\\w+`([^`]*)",
			"tw\\(.*?\\)`([^`]*)"
		],
	},
}
```

[reference](https://github.com/merrickluo/lsp-tailwindcss?tab=readme-ov-file#how-to-set-up-twinmacro)

**Comment by predragnikolic** [comment]
There were similar issues before, like https://github.com/sublimelsp/LSP-tailwindcss/issues/53

Feel free to open a PR and I'll go over it if open.

For now, I will close the issue, thanks for opening it. This issue acts as a guide to setup twin.macro and will certainly help anyone needing to setup twin.macro
