### ISSUE TITLE
tailwindcss lsp in astro file

### ISSUE THREAD

**Issue by dai-re** [sublimelsp/LSP-tailwindcss#68]
![Screenshot_20240427_120350](https://github.com/sublimelsp/LSP-tailwindcss/assets/112737993/b2af6e44-5429-4058-899b-6f69ea513c49)

how to run tailwindcss lsp in astro file?

**Comment by predragnikolic** [comment]
A new version of LSP-tailwindcss is released, it will be available soon on Package Control.

<img width="700" alt="Screenshot 2024-06-28 at 15 35 20" src="https://github.com/sublimelsp/LSP-tailwindcss/assets/22029477/42f19584-5e6e-45b9-a3c3-e96dd978e714">
