### ISSUE TITLE
Unable to get syntax highlighting in .ex Elixir files despite manual "tailwindCSS.includeLanguages"

### ISSUE THREAD

**Issue by dvartic** [sublimelsp/LSP-tailwindcss#75]
Hello,

I am not that familiar with LSP architecture in code editors, so I'm unsure if the problem is related to LSP-tailwindcss or sublimelsp.

As the title indicates, I am unable to get TailwindCSS working in Elixir `.ex` files using the expected `~H` sigil. I have manually configured LSP-tailwindcss with "tailwindCSS.includeLanguages", but still it does not work. I have reviewed a bunch of documentation, tried all sorts of random configs and still can't figure it out.

I think the issue is that, despite configuration, LSP-tailwindcss is not being launched for the file.

Attaching image with configuration:

![Screenshot from 2024-08-20 20-21-45](https://github.com/user-attachments/assets/c73ca902-d056-461b-b64f-8a5e61503779)

**Comment by predragnikolic** [comment]
Hello,
`"tailwindCSS.includeLanguages"` is ok.
However, you need the following scope `source.elixir` (if you use https://packagecontrol.io/packages/Elixir). (source.ex is wrong)
```
{
  "settings": {
    "tailwindCSS.includeLanguages": {
      "elixir": "html"
    }
  },
  "selector": "source.jsx | source.js.react | source.js | source.tsx | source.ts | source.css | source.scss | source.less | text.html.vue | text.html.svelte | text.html.basic | text.html.twig | text.blade | text.html.blade | embedding.php | text.html.rails | text.html.erb | text.haml | text.jinja | text.django | text.html.elixir | source.elixir | text.html.ngx | source.astro"
}
```

**Comment by dvartic** [comment]
> Hello, `"tailwindCSS.includeLanguages"` is ok. However, you need the following scope `source.elixir` (if you use https://packagecontrol.io/packages/Elixir). (source.ex is wrong)
> 
> ```
> {
>   "settings": {
>     "tailwindCSS.includeLanguages": {
>       "elixir": "html"
>     }
>   },
>   "selector": "source.jsx | source.js.react | source.js | source.tsx | source.ts | source.css | source.scss | source.less | text.html.vue | text.html.svelte | text.html.basic | text.html.twig | text.blade | text.html.blade | embedding.php | text.html.rails | text.html.erb | text.haml | text.jinja | text.django | text.html.elixir | source.elixir | text.html.ngx | source.astro"
> }
> ```

Wow so that was it, thank you so much for your help. I was not able to figure it out, I simply deducted that `.ex` was the correct way due to the file extension of elixir files.

Well, sorry for opening an issue with this. Hopefully it helps future devs coming to Sublime and Elixir.
