### ISSUE TITLE
Server crashing

### ISSUE THREAD

**Issue by ChristopherBrownie** [sublimelsp/LSP-tailwindcss#78]
Plugin was working great up until a few weeks ago. I've tried reinstalling with no luck.

![image](https://github.com/user-attachments/assets/8a570b4b-148a-4282-bb6c-7078d0889c68)

Panel output with LSP `log_debug: true` with `-user` and `-project-path` redacted.
> LSP: starting ['/usr/local/bin/node', '/Users/-user/Library/Caches/Sublime Text 3/Package Storage/LSP-tailwindcss/18.0.0/language-server/node_modules/@tailwindcss/language-server/bin/tailwindcss-language-server', '--stdio'] in /Users/-project-path
LSP: LSP-tailwindcss crashed (1 / 5 times in the last 180.0 seconds), exit code 1, exception: None
LSP: starting ['/usr/local/bin/node', '/Users/-user/Library/Caches/Sublime Text 3/Package Storage/LSP-tailwindcss/18.0.0/language-server/node_modules/@tailwindcss/language-server/bin/tailwindcss-language-server', '--stdio'] in /Users/-project-path
LSP: LSP-tailwindcss crashed (2 / 5 times in the last 180.0 seconds), exit code 1, exception: None
LSP: starting ['/usr/local/bin/node', '/Users/-user/Library/Caches/Sublime Text 3/Package Storage/LSP-tailwindcss/18.0.0/language-server/node_modules/@tailwindcss/language-server/bin/tailwindcss-language-server', '--stdio'] in /Users/-project-path
LSP: LSP-tailwindcss crashed (3 / 5 times in the last 180.0 seconds), exit code 1, exception: None
LSP: starting ['/usr/local/bin/node', '/Users/-user/Library/Caches/Sublime Text 3/Package Storage/LSP-tailwindcss/18.0.0/language-server/node_modules/@tailwindcss/language-server/bin/tailwindcss-language-server', '--stdio'] in /Users/-project-path
LSP: LSP-tailwindcss crashed (4 / 5 times in the last 180.0 seconds), exit code 1, exception: None
LSP: starting ['/usr/local/bin/node', '/Users/-user/Library/Caches/Sublime Text 3/Package Storage/LSP-tailwindcss/18.0.0/language-server/node_modules/@tailwindcss/language-server/bin/tailwindcss-language-server', '--stdio'] in /Users/-project-path
LSP: LSP-tailwindcss crashed (5 / 5 times in the last 180.0 seconds), exit code 1, exception: None

**Comment by rchl** [comment]
`LSP: Troubleshoot server` in the command palette might provide useful info.

**Comment by ChristopherBrownie** [comment]
> TypeError: (0, J5. isBuiltin) is not a function
Node. js v18.0.0

Thanks that helped identify the problem, I updated node to the latest `22.8.0` and is now working again. Thank you!

**Comment by rchl** [comment]
a declaration like https://github.com/sublimelsp/LSP-volar/blob/5b595c0f274163600af43f05c5baa14f5e236480/plugin.py#L24-L26 should be added in this package which will give better error message for this issue

**Comment by predragnikolic** [comment]
closed with https://github.com/sublimelsp/LSP-tailwindcss/commit/1b986717c1928eb79476e8d716fabc302fde1642
